from typing import Protocol, Sequence


class HidBackend(Protocol):
    def info(self) -> dict: ...
    def keyboard(self, modifiers: int, keys: Sequence[int]) -> None: ...
    def media(self, code: int) -> None: ...
    def mouse_rel(self, dx: int, dy: int, buttons: int = 0, wheel: int = 0) -> None: ...
    def close(self) -> None: ...
